packages:
  - "apps/*"
  - "packages/*"
  - "!packages/mtg-image-db"

catalog:
  eslint: ^9.20.0
  prettier: ^3.6.2
  typescript: ~5.7
  'typescript-eslint': ^8.24.1
  playwright: ^1.55.1
  '@playwright/test': ^1.55.1