import { existsSync, readFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { PeerServer } from 'peer'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const port = parseInt(process.env.PEERJS_PORT || '9000', 10)
const path = process.env.PEERJS_PATH || '/peerjs'
const nodeEnv = process.env.NODE_ENV || 'development'
const useSSL = process.env.PEERJS_SSL !== 'false' // Default to true in dev

console.log(`[PeerServer] Starting on port ${port} with path ${path}`)
console.log(`[PeerServer] Environment: ${nodeEnv}`)
console.log(`[PeerServer] SSL enabled: ${useSSL}`)

// Try to load SSL certificates generated by mkcert
let sslKey: string | undefined
let sslCert: string | undefined

if (useSSL) {
  // Certificate directory relative to this file
  const certDir = join(__dirname, '../certificates')

  const keyPath = join(certDir, 'dev.pem')
  const certPath = join(certDir, 'cert.pem')

  // Check if certificates exist
  if (existsSync(keyPath) && existsSync(certPath)) {
    try {
      sslKey = readFileSync(keyPath, 'utf-8')
      sslCert = readFileSync(certPath, 'utf-8')
      console.log(`[PeerServer] SSL certificates loaded from ${certDir}`)
      console.log(`[PeerServer] Using key: ${keyPath}, cert: ${certPath}`)
    } catch (_error) {
      console.warn(
        `[PeerServer] Could not read SSL certificates from ${certDir}. ` +
          'Run "bun run generate-certs" to generate them, or set PEERJS_SSL=false to use HTTP.',
      )
      console.warn(`[PeerServer] Falling back to HTTP (ws://)`)
    }
  } else {
    console.warn(
      `[PeerServer] SSL certificates not found in ${certDir}. ` +
        'To enable secure WebSocket (wss://), run "bun run generate-certs" to generate certificates. ' +
        'Falling back to HTTP (ws://) for now.',
    )
  }
}

const peerServerConfig: {
  port: number
  path: string
  allow_discovery: boolean
  sslkey?: string
  sslcert?: string
} = {
  port,
  path,
  allow_discovery: true,
}

if (sslKey && sslCert) {
  peerServerConfig.sslkey = sslKey
  peerServerConfig.sslcert = sslCert
}

const peerServer = PeerServer(peerServerConfig)

peerServer.on('connection', (client) => {
  console.log(`[PeerServer] Client connected: ${client.getId()}`)
})

peerServer.on('disconnect', (client) => {
  console.log(`[PeerServer] Client disconnected: ${client.getId()}`)
})

const protocol = sslKey && sslCert ? 'wss' : 'ws'
console.log(`[PeerServer] PeerServer initialized successfully`)
console.log(
  `[PeerServer] WebSocket URL: ${protocol}://localhost:${port}${path}`,
)
