/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrevIndexRouteImport } from './routes/prev/index'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevIndexRoute = PrevIndexRouteImport.update({
  id: '/prev/',
  path: '/prev/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/prev': typeof PrevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/prev': typeof PrevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/prev/': typeof PrevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$gameId' | '/prev'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$gameId' | '/prev'
  id: '__root__' | '/' | '/game/$gameId' | '/prev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGameIdRoute: typeof GameGameIdRoute
  PrevIndexRoute: typeof PrevIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prev/': {
      id: '/prev/'
      path: '/prev'
      fullPath: '/prev'
      preLoaderRoute: typeof PrevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGameIdRoute: GameGameIdRoute,
  PrevIndexRoute: PrevIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
