openapi: 3.1.0
info:
  title: PeerJS WebSocket Signaling API
  version: 0.3.0
  description: |
    WebSocket-based signaling protocol for coordinating peer-to-peer WebRTC connections.
    Compatible with PeerJS client library v1.x.
    
    Connection URL: `wss://{host}/peerjs?key={apiKey}&id={peerId}&token={token}`
    
    Message format: JSON over WebSocket

servers:
  - url: wss://peerjs.spell-coven.workers.dev
    description: Production Cloudflare Workers endpoint
  - url: ws://localhost:8787
    description: Local development (Miniflare)

paths:
  /peerjs:
    get:
      summary: Establish WebSocket connection
      description: |
        Upgrade HTTP connection to WebSocket for signaling.
        Query parameters are used for authentication and peer identification.
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
          description: API key for authentication (currently unused, reserved for future)
          example: "peerjs"
        - name: id
          in: query
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9-]{1,64}$'
          description: Unique peer identifier (client-provided)
          example: "peer-123-abc"
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: Room token (Discord channel ID)
          example: "1234567890123456789"
      responses:
        '101':
          description: Switching Protocols - WebSocket connection established
          headers:
            Upgrade:
              schema:
                type: string
                enum: [websocket]
            Connection:
              schema:
                type: string
                enum: [Upgrade]
        '400':
          description: Bad Request - Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too Many Requests - Room is full (4 peers maximum)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # Client → Server Messages
    ClientMessage:
      oneOf:
        - $ref: '#/components/schemas/HeartbeatMessage'
        - $ref: '#/components/schemas/OfferMessage'
        - $ref: '#/components/schemas/AnswerMessage'
        - $ref: '#/components/schemas/CandidateMessage'
        - $ref: '#/components/schemas/LeaveMessage'
      discriminator:
        propertyName: type

    HeartbeatMessage:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum: [HEARTBEAT]
      example:
        type: HEARTBEAT

    OfferMessage:
      type: object
      required:
        - type
        - src
        - dst
        - payload
      properties:
        type:
          type: string
          enum: [OFFER]
        src:
          type: string
          description: Source peer ID (sender)
          example: "peer-123-abc"
        dst:
          type: string
          description: Destination peer ID (receiver)
          example: "peer-456-def"
        payload:
          $ref: '#/components/schemas/RTCSessionDescription'
      example:
        type: OFFER
        src: "peer-123-abc"
        dst: "peer-456-def"
        payload:
          type: offer
          sdp: "v=0\r\no=- 123456789 2 IN IP4 127.0.0.1\r\n..."

    AnswerMessage:
      type: object
      required:
        - type
        - src
        - dst
        - payload
      properties:
        type:
          type: string
          enum: [ANSWER]
        src:
          type: string
          description: Source peer ID (sender)
        dst:
          type: string
          description: Destination peer ID (receiver)
        payload:
          $ref: '#/components/schemas/RTCSessionDescription'
      example:
        type: ANSWER
        src: "peer-456-def"
        dst: "peer-123-abc"
        payload:
          type: answer
          sdp: "v=0\r\no=- 987654321 2 IN IP4 127.0.0.1\r\n..."

    CandidateMessage:
      type: object
      required:
        - type
        - src
        - dst
        - payload
      properties:
        type:
          type: string
          enum: [CANDIDATE]
        src:
          type: string
          description: Source peer ID (sender)
        dst:
          type: string
          description: Destination peer ID (receiver)
        payload:
          $ref: '#/components/schemas/RTCIceCandidate'
      example:
        type: CANDIDATE
        src: "peer-123-abc"
        dst: "peer-456-def"
        payload:
          candidate: "candidate:1 1 UDP 2130706431 192.168.1.100 54321 typ host"
          sdpMid: "0"
          sdpMLineIndex: 0

    LeaveMessage:
      type: object
      required:
        - type
        - src
      properties:
        type:
          type: string
          enum: [LEAVE]
        src:
          type: string
          description: Peer ID leaving the room
      example:
        type: LEAVE
        src: "peer-123-abc"

    # Server → Client Messages
    ServerMessage:
      oneOf:
        - $ref: '#/components/schemas/OpenMessage'
        - $ref: '#/components/schemas/ServerOfferMessage'
        - $ref: '#/components/schemas/ServerAnswerMessage'
        - $ref: '#/components/schemas/ServerCandidateMessage'
        - $ref: '#/components/schemas/ServerLeaveMessage'
        - $ref: '#/components/schemas/ExpireMessage'
        - $ref: '#/components/schemas/ServerErrorMessage'
      discriminator:
        propertyName: type

    OpenMessage:
      type: object
      required:
        - type
        - peerId
      properties:
        type:
          type: string
          enum: [OPEN]
        peerId:
          type: string
          description: Confirmed peer ID for this connection
      example:
        type: OPEN
        peerId: "peer-123-abc"

    ServerOfferMessage:
      type: object
      required:
        - type
        - src
        - payload
      properties:
        type:
          type: string
          enum: [OFFER]
        src:
          type: string
          description: Source peer ID (sender)
        payload:
          $ref: '#/components/schemas/RTCSessionDescription'
      example:
        type: OFFER
        src: "peer-456-def"
        payload:
          type: offer
          sdp: "v=0\r\no=- 123456789 2 IN IP4 127.0.0.1\r\n..."

    ServerAnswerMessage:
      type: object
      required:
        - type
        - src
        - payload
      properties:
        type:
          type: string
          enum: [ANSWER]
        src:
          type: string
          description: Source peer ID (sender)
        payload:
          $ref: '#/components/schemas/RTCSessionDescription'
      example:
        type: ANSWER
        src: "peer-456-def"
        payload:
          type: answer
          sdp: "v=0\r\no=- 987654321 2 IN IP4 127.0.0.1\r\n..."

    ServerCandidateMessage:
      type: object
      required:
        - type
        - src
        - payload
      properties:
        type:
          type: string
          enum: [CANDIDATE]
        src:
          type: string
          description: Source peer ID (sender)
        payload:
          $ref: '#/components/schemas/RTCIceCandidate'
      example:
        type: CANDIDATE
        src: "peer-456-def"
        payload:
          candidate: "candidate:1 1 UDP 2130706431 192.168.1.100 54321 typ host"
          sdpMid: "0"
          sdpMLineIndex: 0

    ServerLeaveMessage:
      type: object
      required:
        - type
        - peerId
      properties:
        type:
          type: string
          enum: [LEAVE]
        peerId:
          type: string
          description: Peer ID that left the room
      example:
        type: LEAVE
        peerId: "peer-123-abc"

    ExpireMessage:
      type: object
      required:
        - type
        - peerId
      properties:
        type:
          type: string
          enum: [EXPIRE]
        peerId:
          type: string
          description: Peer ID that timed out
      example:
        type: EXPIRE
        peerId: "peer-123-abc"

    ServerErrorMessage:
      type: object
      required:
        - type
        - payload
      properties:
        type:
          type: string
          enum: [ERROR]
        payload:
          type: object
          required:
            - type
            - message
          properties:
            type:
              type: string
              enum:
                - invalid-message
                - unknown-peer
                - rate-limit-exceeded
                - room-full
                - internal-error
            message:
              type: string
              description: Human-readable error message
      example:
        type: ERROR
        payload:
          type: room-full
          message: "Room has reached maximum capacity (4 peers)"

    # WebRTC Types
    RTCSessionDescription:
      type: object
      required:
        - type
        - sdp
      properties:
        type:
          type: string
          enum: [offer, answer, pranswer, rollback]
        sdp:
          type: string
          description: Session Description Protocol string

    RTCIceCandidate:
      type: object
      required:
        - candidate
      properties:
        candidate:
          type: string
          description: ICE candidate string
        sdpMid:
          type: string
          nullable: true
          description: Media stream identification tag
        sdpMLineIndex:
          type: integer
          nullable: true
          description: Index of the media description in the SDP
        usernameFragment:
          type: string
          nullable: true
          description: ICE username fragment

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
      example:
        error: "room-full"
        message: "Room has reached maximum capacity (4 peers)"

  securitySchemes:
    ApiKey:
      type: apiKey
      in: query
      name: key
      description: API key for authentication (currently unused)

security:
  - ApiKey: []
